import { ClientProvider } from "@/components/providers/client-provider";
import type { Metadata } from "next";
import "./globals.css";
import { Inter as FontSans } from "next/font/google";

import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";
import { Providers } from "@/components/providers";

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <Providers>
            <html lang="en" className="absolute inset-0">
                <body className={cn(fontSans.className, "min-h-full flex flex-col")}>
                    {children}
                    <Toaster position="bottom-center" />
                </body>
            </html>
        </Providers>
    );
}
