// GENERATED by @edgedb/generate v0.5.3

import type {Executor} from "edgedb";

export type CreateEmailVerificationArgs = {
  readonly "user_id": string;
  readonly "code": string;
  readonly "expires_at": Date;
};

export type CreateEmailVerificationReturns = {
  "code": string;
};

export function createEmailVerification(client: Executor, args: CreateEmailVerificationArgs): Promise<CreateEmailVerificationReturns> {
  return client.queryRequiredSingle(`\
select (insert EmailVerificationCode {
      user := <User><uuid>$user_id,
      code := <str>$code,
      expires_at := <datetime>$expires_at
}) {
  code,
}`, args);

}


export type DeleteSessionArgs = {
  readonly "session_id": string;
};

export type DeleteSessionReturns = {
  "id": string;
} | null;

export function deleteSession(client: Executor, args: DeleteSessionArgs): Promise<DeleteSessionReturns> {
  return client.querySingle(`\
delete Session filter .session_id = <str>$session_id;`, args);

}


export type DeleteUserSessionsArgs = {
  readonly "user_id": string;
};

export type DeleteUserSessionsReturns = Array<{
  "id": string;
}>;

export function deleteUserSessions(client: Executor, args: DeleteUserSessionsArgs): Promise<DeleteUserSessionsReturns> {
  return client.query(`\
delete Session filter .user = <User><uuid>$user_id;`, args);

}


export type GetOauthAccountArgs = {
  readonly "provider_user_id": string;
};

export type GetOauthAccountReturns = {
  "user_id": string;
} | null;

export function getOauthAccount(client: Executor, args: GetOauthAccountArgs): Promise<GetOauthAccountReturns> {
  return client.querySingle(`\
select OAuth2Account {
  user_id := .user.id,
}
filter .provider_user_id = <str>$provider_user_id;`, args);

}


export type GetUserSessionsArgs = {
  readonly "user_id": string;
};

export type GetUserSessionsReturns = Array<{
  "id": string;
  "session_id": string;
  "expires_at": Date;
  "user": {
    "id": string;
  };
}>;

export function getUserSessions(client: Executor, args: GetUserSessionsArgs): Promise<GetUserSessionsReturns> {
  return client.query(`\
select Session {
  id,
  session_id,
  expires_at,
  user: {
    id
  }
} filter .user = <User><uuid>$user_id;`, args);

}


export type GetSessionAndUserArgs = {
  readonly "session_id": string;
};

export type GetSessionAndUserReturns = {
  "id": string;
  "session_id": string;
  "expires_at": Date;
  "user": {
    "id": string;
    "email": string;
    "email_verified": boolean;
    "profile": {
      "avatar_url": string | null;
      "cover_url": string | null;
      "display_name": string;
      "tag": string;
    } | null;
  };
} | null;

export function getSessionAndUser(client: Executor, args: GetSessionAndUserArgs): Promise<GetSessionAndUserReturns> {
  return client.querySingle(`\
with
  session := (select Session filter .session_id = <str>$session_id),
  user := (select User filter .id = session.user.id),
select session {
  id,
  session_id,
  expires_at,
  user: {
    id,
    email,
    email_verified,
    profile: {
      avatar_url,
      cover_url,
      display_name,
      tag,
    }
  }
}`, args);

}


export type GetUserWithHashedPasswordArgs = {
  readonly "email": string;
};

export type GetUserWithHashedPasswordReturns = {
  "id": string;
  "hashed_password": string | null;
} | null;

export function getUserWithHashedPassword(client: Executor, args: GetUserWithHashedPasswordArgs): Promise<GetUserWithHashedPasswordReturns> {
  return client.querySingle(`\
select User {
  id,
  hashed_password
}
filter .email = <str>$email`, args);

}


export type SetSessionArgs = {
  readonly "session_id": string;
  readonly "expires_at": Date;
  readonly "user_id": string;
};

export type SetSessionReturns = {
  "id": string;
};

export function setSession(client: Executor, args: SetSessionArgs): Promise<SetSessionReturns> {
  return client.queryRequiredSingle(`\
insert Session {
  session_id := <str>$session_id,
  expires_at := <datetime>$expires_at,
  user := <User><uuid>$user_id,
}`, args);

}


export type UpdateSessionExpirationArgs = {
  readonly "expires_at": Date;
  readonly "session_id": string;
};

export type UpdateSessionExpirationReturns = {
  "id": string;
} | null;

export function updateSessionExpiration(client: Executor, args: UpdateSessionExpirationArgs): Promise<UpdateSessionExpirationReturns> {
  return client.querySingle(`\
update Session
filter .session_id = <str>$session_id
set {
  expires_at := <datetime>$expires_at
}`, args);

}


export type UpdateUserArgs = {
  readonly "email"?: string | null;
  readonly "hashed_password"?: string | null;
  readonly "email_verified"?: boolean | null;
  readonly "user_id": string;
};

export type UpdateUserReturns = {
  "id": string;
} | null;

export function updateUser(client: Executor, args: UpdateUserArgs): Promise<UpdateUserReturns> {
  return client.querySingle(`\
update User
filter .id = <uuid>$user_id
set {
    email := <optional str>$email ?? .email,
    hashed_password := <optional str>$hashed_password ?? .hashed_password,
    email_verified := <optional bool>$email_verified ?? .email_verified,
}`, args);

}


export type VerifyEmailArgs = {
  readonly "code": string;
};

export type VerifyEmailReturns = boolean | null;

export function verifyEmail(client: Executor, args: VerifyEmailArgs): Promise<VerifyEmailReturns> {
  return client.querySingle(`\
with
  email_verification_code := (select EmailVerificationCode filter .user = <User><uuid>global current_user_id),
  expired := email_verification_code.expires_at < datetime_current()
select email_verification_code.code = <str>$code and not expired;`, args);

}


export type CreateCommunityArgs = {
  readonly "name": string;
  readonly "icon_url"?: string | null;
  readonly "cover_url"?: string | null;
};

export type CreateCommunityReturns = {
  "id": string;
};

export function createCommunity(client: Executor, args: CreateCommunityArgs): Promise<CreateCommunityReturns> {
  return client.queryRequiredSingle(`\
select (insert Community {
    name := <str>$name,
    icon_url := <optional str>$icon_url,
    cover_url := <optional str>$cover_url,
    owner := <User>global current_user_id,
    members := (
        select User
        filter .id = global current_user_id
    )
}) {
    id
}`, args);

}



export type GetMyCommunitiesReturns = Array<{
  "name": string;
  "icon_url": string | null;
  "cover_url": string | null;
  "member_count": number;
}>;

export function getMyCommunities(client: Executor): Promise<GetMyCommunitiesReturns> {
  return client.query(`\
select Community {
    name,
    icon_url,
    cover_url,
    member_count := count(.members)
}
filter .members = <User>global current_user_id`);

}


export type CreateProfileArgs = {
  readonly "display_name": string;
  readonly "tag": string;
  readonly "bio"?: string | null;
  readonly "avatar_url"?: string | null;
  readonly "cover_url"?: string | null;
};

export type CreateProfileReturns = {
  "id": string;
};

export function createProfile(client: Executor, args: CreateProfileArgs): Promise<CreateProfileReturns> {
  return client.queryRequiredSingle(`\
insert Profile {
    display_name := <str>$display_name,
    tag := <str>$tag,
    bio := <optional str>$bio,
    avatar_url := <optional str>$avatar_url,
    cover_url := <optional str>$cover_url,
    user := <User>global current_user_id
}`, args);

}


export type UpdateProfileArgs = {
  readonly "display_name"?: string | null;
  readonly "tag"?: string | null;
  readonly "bio"?: string | null;
  readonly "avatar_url"?: string | null;
  readonly "cover_url"?: string | null;
};

export type UpdateProfileReturns = {
  "id": string;
} | null;

export function updateProfile(client: Executor, args: UpdateProfileArgs): Promise<UpdateProfileReturns> {
  return client.querySingle(`\
update Profile
filter .id = global current_user_id
set {
    display_name := <optional str>$display_name ?? .display_name,
    tag := <optional str>$tag ?? .tag,
    bio := <optional str>$bio ?? .bio,
    avatar_url := <optional str>$avatar_url ?? .avatar_url,
    cover_url := <optional str>$cover_url ?? .cover_url,
}`, args);

}


export type DeleteEmailVerificationCodesArgs = {
  readonly "user_id": string;
};

export type DeleteEmailVerificationCodesReturns = {
  "id": string;
} | null;

export function deleteEmailVerificationCodes(client: Executor, args: DeleteEmailVerificationCodesArgs): Promise<DeleteEmailVerificationCodesReturns> {
  return client.querySingle(`\
delete EmailVerificationCode filter .user = <User><uuid>$user_id`, args);

}



export type DeleteExpiredSessionsReturns = Array<{
  "id": string;
}>;

export function deleteExpiredSessions(client: Executor): Promise<DeleteExpiredSessionsReturns> {
  return client.query(`\
delete Session filter .expires_at < datetime_current();`);

}


export type CreateUserArgs = {
  readonly "email": string;
  readonly "hashed_password"?: string | null;
  readonly "email_verified": boolean;
};

export type CreateUserReturns = {
  "id": string;
};

export function createUser(client: Executor, args: CreateUserArgs): Promise<CreateUserReturns> {
  return client.queryRequiredSingle(`\
insert User {
  email := <str>$email,
  hashed_password := <optional str>$hashed_password,
  email_verified := <bool>$email_verified,
}`, args);

}


export type CreateOauthAccountArgs = {
  readonly "provider": string;
  readonly "provider_user_id": string;
  readonly "user_id": string;
};

export type CreateOauthAccountReturns = {
  "id": string;
};

export function createOauthAccount(client: Executor, args: CreateOauthAccountArgs): Promise<CreateOauthAccountReturns> {
  return client.queryRequiredSingle(`\
insert OAuth2Account {
  provider := <str>$provider,
  provider_user_id := <str>$provider_user_id,
  user := <User><uuid>$user_id,
}`, args);

}
